name: Build and test

on:
  workflow_dispatch:
  schedule:
    - cron: '45 16 * * *'
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0
    - name: Download album list
      shell: pwsh
      run: |
        dotnet run `
          --project BandcampDownloader/BandcampDownloader.csproj `
          --configuration Release `
          --username "${{ secrets.BANDCAMP_USERNAME }}" `
          --password "${{ secrets.BANDCAMP_PASSWORD }}" `
          | Tee-Object -FilePath "Api.Tests/Actual.txt"
    - name: Unit tests
      run: dotnet test --verbosity normal
