name: Build and test

on:
  workflow_dispatch:
  schedule:
    - cron: '45 16 * * *'
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0
    - name: Unit tests
      run: dotnet test --verbosity normal
    - name: End-to-end tests
      shell: pwsh
      run: |
        $output = dotnet run `
          --project BandcampDownloader/BandcampDownloader.csproj
          --configuration Release `
          --username "${{ secrets.BANDCAMP_USERNAME }}" `
          --password "${{ secrets.BANDCAMP_PASSWORD }}" `
          | Out-String

        $expected = Get-Content "Testcases/Albums.txt" -Raw

        if ($output.Contains($expected)) {
            Write-Host "✅ Albums.txt content found in output"
        } else {
            Write-Host "❌ Albums.txt content not found in output"
            exit 1
        }
